# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.cache/wt [current_project]
set_property parent.project_path /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.runs/Mnozarka_synth_1/Mnozarka.dcp
set_property used_in_implementation false [get_files /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.runs/Mnozarka_synth_1/Mnozarka.dcp]
read_verilog -library xil_defaultlib /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.srcs/sources_1/new/myHough.v
synth_design -top myHough -part xc7z010clg400-1
write_checkpoint -noxdef myHough.dcp
catch { report_utilization -file myHough_utilization_synth.rpt -pb myHough_utilization_synth.pb }
