# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.srcs/sources_1/ip/Mnozarka/Mnozarka.xci
# IP: The module: 'Mnozarka' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.srcs/sources_1/ip/Mnozarka/Mnozarka_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mnozarka'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.srcs/sources_1/ip/Mnozarka/Mnozarka.xci
# IP: The module: 'Mnozarka' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/psra/kubicz/hough-hw-filip/Hough_Filip.srcs/sources_1/ip/Mnozarka/Mnozarka_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mnozarka'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
