# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base_zynq_design/base_zynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design || ORIG_REF_NAME==base_zynq_design}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_blk_mem_gen_0_0 || ORIG_REF_NAME==base_zynq_design_blk_mem_gen_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_zynq_design_axi_bram_ctrl_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0/base_zynq_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_xbar_0 || ORIG_REF_NAME==base_zynq_design_xbar_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_0 || ORIG_REF_NAME==base_zynq_design_auto_pc_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_1 || ORIG_REF_NAME==base_zynq_design_auto_pc_1}]

# XDC: bd/base_zynq_design/base_zynq_design_ooc.xdc
